#pragma once

#include "rep_counter_source.h"
#include "logos_ui_plugin_context.h"

// Universal ui_qml backend: the .rep view contract and this class are the whole
// hand-written surface. The *Interface.h and *Plugin glue (Q_PLUGIN_METADATA,
// initLogos, QtRO source registration) are generated by logos-qt-generator from
// metadata.json#codegen.
class CounterBackend : public CounterSimpleSource,
                       public LogosUiPluginContext {
    Q_OBJECT

public:
    explicit CounterBackend(QObject* parent = nullptr);

public slots:
    void increment() override;
};
